# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Integration tests: stdlib-only OCI hook entrypoint — end-to-end story.

Exercises the complete flow introduced by the pre-generated ruleset architecture:

1. ``pre_start()`` writes ``ruleset.nft`` before any container starts.
2. The OCI hook (stdlib-only, ``#!/usr/bin/env python3``) applies the
   pre-generated ruleset and discovers the container gateway from
   ``/proc/{pid}/net/route``.
3. ``shield_up()`` repopulates the gateway set from the persisted
   ``gateway`` file after re-applying the ruleset.
"""

import os
import sys
from pathlib import Path
from unittest import mock

import pytest

from terok_shield import Shield, ShieldConfig, state
from tests.testnet import BLOCKED_TARGET_HTTP

from ..conftest import CTR_PREFIX, hooks_unavailable, nft_missing, podman_missing
from ..helpers import assert_blocked


@pytest.mark.needs_podman
@pytest.mark.needs_internet
@pytest.mark.needs_hooks
@podman_missing
@nft_missing
@hooks_unavailable
@pytest.mark.usefixtures("nft_in_netns")
class TestHookEntrypointStory:
    """Story: stdlib-only hook applies pre-generated ruleset and discovers gateway."""

    @mock.patch("terok_shield.mode_hook.has_global_hooks", return_value=True)
    def test_pre_start_writes_ruleset_nft(
        self, _hgh: mock.Mock, shield_env: Path, _pull_image: None
    ) -> None:
        """pre_start must write ruleset.nft before the container starts."""
        name = f"{CTR_PREFIX}-ruleset-{os.getpid()}"
        sd = shield_env / "containers" / name
        shield = Shield(ShieldConfig(state_dir=sd))
        shield.pre_start(name)

        ruleset = state.ruleset_path(sd)
        assert ruleset.exists(), "pre_start must write ruleset.nft"
        content = ruleset.read_text()
        assert "terok_shield" in content
        assert "gateway_v4" in content
        assert "gateway_v6" in content

    def test_full_story_hook_applies_ruleset_and_discovers_gateway(
        self, shielded_container: str, shield_env: Path
    ) -> None:
        """Full story: hook applies pre-generated ruleset, writes gateway file,
        shield_up repopulates gateway_v4 set, default-deny is enforced throughout.
        """
        name = shielded_container
        sd = shield_env / "containers" / name
        shield = Shield(ShieldConfig(state_dir=sd))

        # 1. Ruleset was pre-generated by pre_start (before container started)
        assert state.ruleset_path(sd).exists(), "ruleset.nft must exist after pre_start"

        # 2. Hook applied the ruleset — terok_shield table is present
        rules = shield.rules(name)
        assert "terok_shield" in rules
        assert "gateway_v4" in rules  # set defined even when empty

        # 3. Default-deny: outbound traffic to non-allowed targets is blocked
        assert_blocked(name, BLOCKED_TARGET_HTTP)

        # 4. Gateway discovery: gateway file written iff a default route exists
        gw_file = state.gateway_path(sd)
        if gw_file.exists():
            gw = gw_file.read_text().strip()
            assert gw, "gateway file must contain a non-empty IP"
            assert gw in rules, f"Discovered gateway {gw!r} must appear in live ruleset"

        # 5. shield_up re-applies the ruleset and repopulates the gateway set
        shield.up(name)
        rules_after_up = shield.rules(name)
        assert "gateway_v4" in rules_after_up
        if gw_file.exists():
            gw = gw_file.read_text().strip()
            assert gw in rules_after_up, "shield_up must repopulate gateway_v4 set"

        # Default-deny must hold after shield_up as well
        assert_blocked(name, BLOCKED_TARGET_HTTP)

    @mock.patch("terok_shield.mode_hook.has_global_hooks", return_value=True)
    def test_hook_entrypoint_is_stdlib_only(
        self, _hgh: mock.Mock, shield_env: Path, _pull_image: None
    ) -> None:
        """The installed hook script must use /usr/bin/env python3 and import no terok_shield modules."""
        name = f"{CTR_PREFIX}-ep-check-{os.getpid()}"
        sd = shield_env / "containers" / name
        Shield(ShieldConfig(state_dir=sd)).pre_start(name)

        entrypoint = state.hook_entrypoint(sd)
        assert entrypoint.exists(), "pre_start must install the hook entrypoint script"
        content = entrypoint.read_text()
        assert content.splitlines()[0] == "#!/usr/bin/env python3", (
            "Hook entrypoint must start with #!/usr/bin/env python3"
        )
        assert "import terok_shield" not in content, (
            "Hook entrypoint must not import terok_shield (stdlib only)"
        )
        assert sys.executable not in content, (
            "Hook entrypoint must not bake in the current Python interpreter path"
        )
