#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0
"""OCI hook: apply pre-generated terok-shield nft ruleset.

Applies ``ruleset.nft`` (written by ``pre_start()``), discovers the container
gateway dynamically from ``/proc/{pid}/net/route``, and optionally starts
dnsmasq if ``dnsmasq.conf`` is present in the state directory.

Zero ``terok_shield.*`` imports — only ``python3`` (stdlib), ``nft``,
``nsenter``, and optionally ``dnsmasq`` are required.  This makes the hook
independent of any specific Python virtualenv or install method.

``nsenter -U -n -t <pid>`` is used to enter both the container's user
namespace and network namespace in a single call.  The ``-U`` flag enters
the user namespace that owns the network namespace, granting
``CAP_NET_ADMIN`` (required by nft) and ``CAP_NET_BIND_SERVICE``
(required by dnsmasq on port 53) without relying on ``podman`` being
present in the OCI hook's execution environment.
"""

import ipaddress
import json
import os
import shutil
import socket
import struct
import subprocess  # nosec B404
import sys
from pathlib import Path

# These constants are intentionally duplicated from src/terok_shield/state.py
# so this script stays stdlib-only (no terok_shield imports).  Keep in sync:
#   _BUNDLE_VERSION  ↔  state.BUNDLE_VERSION
#   "ruleset.nft"    ↔  state.ruleset_path()
#   "gateway"        ↔  state.gateway_path()
#   "dnsmasq.conf"   ↔  state.dnsmasq_conf_path()
#   "dnsmasq.pid"    ↔  state.dnsmasq_pid_path()
_ANN_STATE_DIR = "terok.shield.state_dir"
_ANN_VERSION = "terok.shield.version"
_BUNDLE_VERSION = 3
_TABLE = "inet terok_shield"


def _find_nsenter() -> str:
    """Return the path to the nsenter binary, falling back to /usr/bin/nsenter."""
    return shutil.which("nsenter") or "/usr/bin/nsenter"


def _find_nft() -> str:
    """Return the path to the nft binary, falling back to /usr/sbin/nft."""
    return shutil.which("nft") or "/usr/sbin/nft"


def _find_dnsmasq() -> str:
    """Return the path to the dnsmasq binary, falling back to /usr/sbin/dnsmasq."""
    return shutil.which("dnsmasq") or "/usr/sbin/dnsmasq"


def _nsenter(pid: str, *cmd: str, stdin: str | None = None) -> None:
    """Run *cmd* inside the container's user+network namespace via nsenter.

    ``-U`` enters the user namespace that owns the network namespace, granting
    ``CAP_NET_ADMIN`` and ``CAP_NET_BIND_SERVICE`` without requiring ``podman``
    to be in PATH.  ``-n`` enters the network namespace itself.  Both use the
    target process PID (``-t <pid>``).

    Captures stderr so error details appear in the hook's log rather than
    being silently swallowed by the OCI runtime (crun/runc).
    """
    result = subprocess.run(  # nosec B603
        [_find_nsenter(), "-U", "-n", "-t", pid, "--", *cmd],
        input=stdin,
        text=True,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        stderr = result.stderr.strip()
        raise RuntimeError(
            f"nsenter command failed (exit {result.returncode})"
            + (f":\n{stderr}" if stderr else "")
        )


def _read_gateway(pid: str) -> str:
    """Read the default IPv4 gateway from the container's routing table.

    Parses ``/proc/{pid}/net/route`` (the kernel routing table for the
    container's network namespace).  Returns an empty string when no default
    route is present (e.g. pasta mode) or when parsing fails — fail-closed:
    the nft ruleset is still applied, gateway sets stay empty.
    """
    try:
        for line in Path(f"/proc/{pid}/net/route").read_text().splitlines()[1:]:
            fields = line.split()
            if len(fields) >= 3 and fields[1] == "00000000":
                gw = socket.inet_ntoa(struct.pack("=I", int(fields[2], 16)))
                ipaddress.ip_address(gw)  # validate — raises ValueError if malformed
                return gw
    except (OSError, ValueError, struct.error):
        pass
    return ""


def _createruntime(pid: str, sd: Path) -> None:
    """Apply the pre-generated ruleset and optionally start dnsmasq."""
    ruleset = sd / "ruleset.nft"
    if not ruleset.exists():
        raise RuntimeError(f"ruleset.nft not found: {ruleset}")
    nft = _find_nft()
    _nsenter(pid, nft, "-f", str(ruleset))

    # Discover gateway from routing table, persist, and populate nft set.
    # Clear any stale file from a previous run so shield_up() doesn't
    # repopulate the wrong gateway into a reused state directory.
    gateway_file = sd / "gateway"
    gw = _read_gateway(pid)
    if gw:
        gateway_file.write_text(f"{gw}\n")
        _nsenter(pid, nft, "add", "element", _TABLE, "gateway_v4", f"{{ {gw} }}")
    else:
        try:
            gateway_file.unlink()
        except OSError:
            pass

    # Start per-container dnsmasq if config was pre-generated by pre_start()
    dnsmasq_conf = sd / "dnsmasq.conf"
    if dnsmasq_conf.exists():
        _nsenter(pid, _find_dnsmasq(), f"--conf-file={dnsmasq_conf}")
        try:
            Path(f"/proc/{pid}/root/etc/resolv.conf").write_text("nameserver 127.0.0.1\nndots:0\n")
        except OSError:
            pass  # non-fatal: container DNS may still work via default


def _is_our_dnsmasq(pid_int: int, conf_path: Path) -> bool:
    """Return True if pid_int is a dnsmasq process using our conf file.

    Parses ``/proc/{pid}/cmdline`` as a NUL-separated argv vector.
    Requires argv[0] to be the dnsmasq binary (exact name or absolute path)
    and ``--conf-file=<our-conf>`` to be present as a separate argument.
    Mirrors ``terok_shield.dnsmasq._is_our_dnsmasq()`` without any imports.
    """
    conf_arg = b"--conf-file=" + str(conf_path).encode()
    try:
        raw = Path(f"/proc/{pid_int}/cmdline").read_bytes()
    except OSError:
        return False
    args = raw.rstrip(b"\x00").split(b"\x00")
    if not args:
        return False
    exe = args[0]
    return (exe == b"dnsmasq" or exe.endswith(b"/dnsmasq")) and conf_arg in args


def _poststop(sd: Path) -> None:
    """Send SIGTERM to the per-container dnsmasq process (best-effort).

    Verifies PID identity against ``/proc/{pid}/cmdline`` before signalling
    to avoid hitting an unrelated process when the original dnsmasq PID is
    recycled after container stop.
    """
    pid_file = sd / "dnsmasq.pid"
    conf_path = sd / "dnsmasq.conf"
    if not pid_file.exists():
        return
    try:
        pid_int = int(pid_file.read_text().strip())
    except (ValueError, OSError):
        return
    if not _is_our_dnsmasq(pid_int, conf_path):
        try:
            pid_file.unlink()
        except OSError:
            pass
        return
    try:
        os.kill(pid_int, 15)
    except OSError:
        pass


def _log(msg: str, log_path: Path | None = None) -> None:
    """Write *msg* to stderr and to a persistent log file (best-effort).

    The OCI runtime (crun/runc) typically swallows hook stderr.  Writing to a
    file in the state directory (or /tmp as fallback) makes errors visible.
    """
    print(msg, file=sys.stderr)
    path = log_path or Path("/tmp/terok-hook-error.log")  # nosec B108
    try:
        with path.open("a") as f:
            f.write(f"{msg}\n")
    except OSError:
        pass


def main() -> int:
    """OCI hook entry point: dispatch to createRuntime or poststop handler."""
    stage = sys.argv[1] if len(sys.argv) > 1 else "createRuntime"
    try:
        oci = json.load(sys.stdin)
    except ValueError as exc:
        _log(f"terok-shield hook: bad OCI state: {exc}")
        return 1

    if not isinstance(oci, dict):
        _log("terok-shield hook: OCI state must be a JSON object")
        return 1

    ann = oci.get("annotations", {})
    if not isinstance(ann, dict):
        _log("terok-shield hook: annotations must be a JSON object")
        return 1

    sd_str = ann.get(_ANN_STATE_DIR, "")
    if not sd_str:
        _log("terok-shield hook: missing state_dir annotation")
        return 1
    try:
        _p = Path(sd_str)
        if not _p.is_absolute():
            raise ValueError(f"state_dir must be absolute: {sd_str!r}")
        sd = _p.resolve()
    except (ValueError, OSError) as exc:
        _log(f"terok-shield hook: invalid state_dir: {exc}")
        return 1

    # All subsequent errors go to <state_dir>/hook-error.log so they survive
    # even when the OCI runtime does not forward the hook's stderr.
    log_path = sd / "hook-error.log"

    ver = ann.get(_ANN_VERSION, "")
    if not ver or str(ver) != str(_BUNDLE_VERSION):
        _log(
            f"terok-shield hook: bundle version {ver!r} != {_BUNDLE_VERSION}. Re-run pre_start().",
            log_path,
        )
        return 1
    try:
        if stage == "poststop":
            _poststop(sd)
        else:
            pid = str(oci.get("pid") or "")
            if not pid:
                _log("terok-shield hook: missing pid in OCI state", log_path)
                return 1
            _createruntime(pid, sd)
    except Exception as exc:  # noqa: BLE001
        _log(f"terok-shield hook: {exc}", log_path)
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
