#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0
"""OCI hook: apply pre-generated terok-shield nft ruleset. Stdlib only.

Applies ``ruleset.nft`` (written by ``pre_start()``), discovers the container
gateway dynamically from ``/proc/{pid}/net/route``, and optionally starts
dnsmasq if ``dnsmasq.conf`` is present in the state directory.

Zero ``terok_shield.*`` imports — only ``python3`` (stdlib), ``nft``, ``nsenter``,
and optionally ``dnsmasq`` are required.  This makes the hook independent of any
specific Python virtualenv or install method.
"""

import ipaddress
import json
import os
import shutil
import socket
import struct
import subprocess  # nosec B404
import sys
from pathlib import Path

_ANN_STATE_DIR = "terok.shield.state_dir"
_ANN_VERSION = "terok.shield.version"
_BUNDLE_VERSION = 3
_TABLE = "inet terok_shield"


def _find_nsenter() -> str:
    """Return the path to the nsenter binary, falling back to /usr/bin/nsenter."""
    return shutil.which("nsenter") or "/usr/bin/nsenter"


def _find_nft() -> str:
    """Return the path to the nft binary, falling back to /usr/sbin/nft."""
    return shutil.which("nft") or "/usr/sbin/nft"


def _find_dnsmasq() -> str:
    """Return the path to the dnsmasq binary, falling back to /usr/sbin/dnsmasq."""
    return shutil.which("dnsmasq") or "/usr/sbin/dnsmasq"


def _nsenter(pid: str, *cmd: str, stdin: str | None = None) -> None:
    """Run *cmd* inside the container's network namespace via nsenter."""
    subprocess.run(  # nosec B603
        [_find_nsenter(), "-t", pid, "-n", "--", *cmd],
        input=stdin,
        text=stdin is not None,
        check=True,
    )


def _read_gateway(pid: str) -> str:
    """Read the default IPv4 gateway from the container's routing table.

    Parses ``/proc/{pid}/net/route`` (the kernel routing table for the
    container's network namespace).  Returns an empty string when no default
    route is present (e.g. pasta mode) or when parsing fails — fail-closed:
    the nft ruleset is still applied, gateway sets stay empty.
    """
    try:
        for line in Path(f"/proc/{pid}/net/route").read_text().splitlines()[1:]:
            fields = line.split()
            if len(fields) >= 3 and fields[1] == "00000000":
                gw = socket.inet_ntoa(struct.pack("=I", int(fields[2], 16)))
                ipaddress.ip_address(gw)  # validate — raises ValueError if malformed
                return gw
    except (OSError, ValueError, struct.error):
        pass
    return ""


def _createruntime(pid: str, sd: Path) -> None:
    """Apply the pre-generated ruleset and optionally start dnsmasq."""
    ruleset = sd / "ruleset.nft"
    if not ruleset.exists():
        raise RuntimeError(f"ruleset.nft not found: {ruleset}")
    nft = _find_nft()
    _nsenter(pid, nft, "-f", str(ruleset))

    # Discover gateway from routing table, persist, and populate nft set
    gw = _read_gateway(pid)
    if gw:
        (sd / "gateway").write_text(f"{gw}\n")
        _nsenter(pid, nft, "add", "element", _TABLE, "gateway_v4", f"{{ {gw} }}")

    # Start per-container dnsmasq if config was pre-generated by pre_start()
    dnsmasq_conf = sd / "dnsmasq.conf"
    if dnsmasq_conf.exists():
        _nsenter(pid, _find_dnsmasq(), f"--conf-file={dnsmasq_conf}")
        try:
            Path(f"/proc/{pid}/root/etc/resolv.conf").write_text("nameserver 127.0.0.1\nndots:0\n")
        except OSError:
            pass  # non-fatal: container DNS may still work via default


def _poststop(sd: Path) -> None:
    """Send SIGTERM to the per-container dnsmasq process (best-effort)."""
    pid_file = sd / "dnsmasq.pid"
    if pid_file.exists():
        try:
            os.kill(int(pid_file.read_text().strip()), 15)
        except (ProcessLookupError, ValueError, OSError):
            pass


def main() -> int:
    """OCI hook entry point: dispatch to createRuntime or poststop handler."""
    stage = sys.argv[1] if len(sys.argv) > 1 else "createRuntime"
    try:
        oci = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError) as exc:
        print(f"terok-shield hook: bad OCI state: {exc}", file=sys.stderr)
        return 1

    ann = oci.get("annotations", {})
    sd_str = ann.get(_ANN_STATE_DIR, "")
    if not sd_str:
        print("terok-shield hook: missing state_dir annotation", file=sys.stderr)
        return 1

    ver = ann.get(_ANN_VERSION, "")
    if ver and str(ver) != str(_BUNDLE_VERSION):
        print(
            f"terok-shield hook: bundle version {ver!r} != {_BUNDLE_VERSION}. Re-run pre_start().",
            file=sys.stderr,
        )
        return 1

    sd = Path(sd_str)
    try:
        if stage == "poststop":
            _poststop(sd)
        else:
            pid = str(oci.get("pid") or "")
            if not pid:
                print("terok-shield hook: missing pid in OCI state", file=sys.stderr)
                return 1
            _createruntime(pid, sd)
    except Exception as exc:  # noqa: BLE001
        print(f"terok-shield hook: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
