version = 1

[[annotations]]
path = [
  "**/*.md",
  "**/*.yml",
  "**/*.yaml",
  "**/*.toml",
  "**/*.json",
  "**/*.lock",
  "**/*.txt",
  "**/*.nft",
  "**/*.css",
  ".gitignore",
  "MANIFEST.in",
  "Makefile",
  "vulture_whitelist.py",
]
SPDX-FileCopyrightText = "2026 Jiri Vyskocil"
SPDX-License-Identifier = "Apache-2.0"
