# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Per-container dnsmasq lifecycle: config generation, launch, and cleanup.

dnsmasq runs inside the container's network namespace (via ``nsenter``),
listens on ``127.0.0.1:53``, and uses ``--nftset`` to auto-populate nft
allow sets on every DNS resolution.  This handles IP rotation that
static pre-start resolution cannot.

This module is the single owner of dnsmasq config format and CLI args.
"""

from __future__ import annotations

import os
import re
import signal
from pathlib import Path
from typing import TYPE_CHECKING

from . import state
from .nft_constants import DNSMASQ_BIND, NFT_TABLE_NAME

if TYPE_CHECKING:
    from .run import CommandRunner

# ── Constants ────────────────────────────────────────────

# Strict domain label validation (RFC 1035 + wildcards).
# Allows: a-z, 0-9, hyphens, dots, leading wildcard (*.).
_DOMAIN_RE = re.compile(r"^(\*\.)?([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)*[a-zA-Z]{2,}$")


# ── Config generation ────────────────────────────────────


def _validate_domain(domain: str) -> str:
    """Validate a domain name against injection.

    Raises ValueError on invalid input.
    """
    d = domain.strip().lower()
    if not d:
        raise ValueError("Empty domain name")
    if not _DOMAIN_RE.fullmatch(d):
        raise ValueError(f"Invalid domain name: {d!r}")
    return d


def nftset_entry(domain: str) -> str:
    """Generate a dnsmasq ``nftset`` config line for a domain.

    Maps A records to the IPv4 allow set and AAAA records to the IPv6
    allow set.  dnsmasq automatically matches the domain and all its
    subdomains.

    Example::

        nftset=/github.com/4#inet#terok_shield#allow_v4,6#inet#terok_shield#allow_v6
    """
    domain = _validate_domain(domain)
    # Strip leading wildcard — dnsmasq nftset inherently matches subdomains.
    if domain.startswith("*."):
        domain = domain[2:]
    return f"nftset=/{domain}/4#inet#{NFT_TABLE_NAME}#allow_v4,6#inet#{NFT_TABLE_NAME}#allow_v6"


def generate_config(
    upstream_dns: str,
    domains: list[str],
    pid_path: Path,
) -> str:
    """Generate a complete dnsmasq configuration.

    Args:
        upstream_dns: Upstream DNS forwarder (pasta or slirp4netns address).
        domains: Domain names for ``--nftset`` auto-population.
        pid_path: Path for the dnsmasq PID file.
    """
    lines = [
        f"# Generated by terok-shield (pid {os.getpid()})",
        f"listen-address={DNSMASQ_BIND}",
        "port=53",
        "bind-interfaces",
        "no-resolv",
        "no-hosts",
        f"server={upstream_dns}",
        f"pid-file={pid_path}",
    ]
    for domain in domains:
        try:
            lines.append(nftset_entry(domain))
        except ValueError:
            continue  # skip invalid domains silently
    return "\n".join(lines) + "\n"


# ── Lifecycle ────────────────────────────────────────────


def launch(
    runner: CommandRunner,
    pid: str,
    state_dir: Path,
    upstream_dns: str,
    domains: list[str],
) -> None:
    """Generate config and launch dnsmasq in the container's network namespace.

    dnsmasq daemonizes and writes its PID to the state directory.
    If dnsmasq lacks ``--nftset`` support, it will fail immediately with
    a clear "bad command line options" error (fail-closed).

    Args:
        runner: Command runner for subprocess calls.
        pid: Container PID (for nsenter).
        state_dir: Per-container state directory.
        upstream_dns: Upstream DNS forwarder address.
        domains: Domain names for nftset auto-population.

    Raises:
        RuntimeError: If dnsmasq fails to start or PID file is not written.
    """
    conf_path = state.dnsmasq_conf_path(state_dir)
    pid_path = state.dnsmasq_pid_path(state_dir)

    config = generate_config(upstream_dns, domains, pid_path)
    conf_path.write_text(config)

    # Launch dnsmasq inside the container's network namespace.
    # --keep-in-foreground is NOT used: dnsmasq daemonizes and writes PID.
    cmd = [
        "nsenter",
        "-t",
        pid,
        "-n",
        "--",
        "dnsmasq",
        f"--conf-file={conf_path}",
    ]
    runner.run(cmd, check=True)

    if not pid_path.is_file():
        raise RuntimeError(
            f"dnsmasq started but PID file not written at {pid_path}. "
            "The container's DNS may not be functional."
        )


def _read_pid(state_dir: Path) -> int | None:
    """Read the dnsmasq PID from state, or None if missing/invalid."""
    pid_path = state.dnsmasq_pid_path(state_dir)
    try:
        return int(pid_path.read_text().strip())
    except (OSError, ValueError):
        return None


def kill(state_dir: Path) -> None:
    """Kill dnsmasq for a container (best-effort cleanup).

    Reads the PID from the state directory and sends SIGTERM.
    Silently ignores missing PID files, stale PIDs, and permission errors.

    Needed because dnsmasq runs in the host PID namespace (we only
    ``nsenter -n`` into the network namespace).  When the container stops,
    podman kills container-PID-namespace processes, but dnsmasq is NOT
    among them — it becomes an orphan with a broken network socket.
    """
    pid_int = _read_pid(state_dir)
    if pid_int is None:
        return
    try:
        os.kill(pid_int, signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        pass


def reload(state_dir: Path, upstream_dns: str, domains: list[str]) -> None:
    """Regenerate dnsmasq config and signal the daemon to reload.

    Sends SIGHUP to the running dnsmasq, which re-reads its config file.
    No-op if dnsmasq is not running (PID file absent).

    Args:
        state_dir: Per-container state directory.
        upstream_dns: Upstream DNS forwarder address.
        domains: Updated domain names for nftset auto-population.
    """
    pid_int = _read_pid(state_dir)
    if pid_int is None:
        return

    # Regenerate config, then signal dnsmasq to re-read it
    pid_path = state.dnsmasq_pid_path(state_dir)
    conf_path = state.dnsmasq_conf_path(state_dir)
    conf_path.write_text(generate_config(upstream_dns, domains, pid_path))
    try:
        os.kill(pid_int, signal.SIGHUP)
    except (ProcessLookupError, PermissionError):
        pass  # dnsmasq already dead; next container start will relaunch


def add_domain(state_dir: Path, domain: str) -> bool:
    """Append a domain to the profile.domains file.

    Returns True if the domain was added, False if already present.
    """
    domain = _validate_domain(domain)
    domains_path = state.profile_domains_path(state_dir)
    existing = _read_domains(domains_path)
    if domain in existing:
        return False
    with domains_path.open("a") as f:
        f.write(f"{domain}\n")
    return True


def remove_domain(state_dir: Path, domain: str) -> bool:
    """Remove a domain from the profile.domains file.

    Returns True if the domain was removed, False if not found.
    """
    domain = _validate_domain(domain)
    domains_path = state.profile_domains_path(state_dir)
    existing = _read_domains(domains_path)
    if domain not in existing:
        return False
    existing.remove(domain)
    domains_path.write_text("\n".join(existing) + "\n" if existing else "")
    return True


def _read_domains(domains_path: Path) -> list[str]:
    """Read domain names from a domains file."""
    if not domains_path.is_file():
        return []
    return [line.strip() for line in domains_path.read_text().splitlines() if line.strip()]


def write_resolv_conf(pid: str, nameserver: str = DNSMASQ_BIND) -> None:
    """Overwrite the container's resolv.conf to point to dnsmasq.

    Safety measure backing up the ``--dns`` podman flag.  Writes directly
    to ``/proc/{pid}/root/etc/resolv.conf`` from the host side.
    """
    resolv_path = Path(f"/proc/{pid}/root/etc/resolv.conf")
    resolv_path.write_text(f"nameserver {nameserver}\n")
